name: health_iq
description: A health tracking application for managing personal health metrics
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.1.4
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.0
  http: ^1.2.2
  fl_chart: ^0.69.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
